name = input("이름을 입력하세요: ")
num = int(input("학번을 입력하세요: "))
major = input("학과를 입력하세요: ")
uni = input("학교를 입력하세요: ")
grade = input("학년을 입력하세요: ")

print("")
print("<출력>")
print("이름: ",name)
print("학번: ",num)
print("학과: ",major)
print("학교: ",uni)
print("학년: ",grade)